on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited
  
name: PR Checks

jobs:
  validate:
    uses: ./.github/workflows/validate.yml