on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited
  
name: PR Checks

jobs:
  validate:
    # uses: ./.github/workflows/validate.yml
    runs-on: ubuntu-latest
    steps:
      - name: Run PR checks
        run: echo "Running PR checks"